function footin = footInPlate(trial, fp, platefoot)
arguments
    trial Trial
    fp forcePlatformType2
    platefoot (:, 3, 2) double
end

fratio = trial.NSamples/trial.NFrames;

temp = diff(and(and(...
            and(platefoot(:, 1, 1) > fp.Corners(1, 1), platefoot(:, 1, 1) < fp.Corners(2, 1)),...
            and(platefoot(:, 2, 1) < fp.Corners(1, 2), platefoot(:, 2, 1) > fp.Corners(4, 2))...
),...
and(...
            and(platefoot(:, 1, 2) > fp.Corners(1, 1), platefoot(:, 1, 2) < fp.Corners(2, 1)),...
            and(platefoot(:, 2, 2) < fp.Corners(1, 2), platefoot(:, 2, 2) > fp.Corners(4, 2))...
)));

footin = zeros(fp.NSamples, 1);
footin((find(temp == 1)+1)*fratio : (find(temp == -1))*fratio) = 1;
end